# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Lm2oJ7mVo9Vs-M5qib1vGWgH19YtPEw
"""

#Q1

roll_number = 1024170348
digits = [int(x) for x in str(roll_number)]
L = [d*10 for d in digits]
print("Initial L:", L)

L.append(100)
print("After append:", L)

L.insert(2, 25)
print("After insert:", L)

L.remove(40)
print("After remove:", L)

L.pop(3)
print("After pop:", L)

L.sort()
print("Ascending:", L)

L.sort(reverse=True)
print("Descending:", L)

print("First three:", L[:3])
print("Last three:", L[-3:])

avg = sum(L)/len(L)
new_list = [x for x in L if x > avg]
print("Average:", avg)
print("Greater than avg:", new_list)

#Q2

roll_number = 1024170348
digits = [int(x) for x in str(roll_number)]
L = [d*10 for d in digits]

scores = tuple(L[:8])
print("Scores tuple:", scores)

print("Highest:", max(scores), "Index:", scores.index(max(scores)))
print("Lowest:", min(scores), "Count:", scores.count(min(scores)))

rev_list = list(scores[::-1])
print("Reversed as list:", rev_list)


x = int(input("Enter a score: "))
if x in scores:
    print("Found at index:", scores.index(x))
else:
    print("Not present")

try:
    scores[0] = 100
except TypeError as e:
    print("Error:", e)


first, second, *rest = scores
print("First:", first)
print("Second:", second)
print("Remaining:", rest)

#Q3

import random
import math
from collections import Counter

roll_number = 1024170348
random.seed(roll_number)

nums = [random.randint(100, 900) for _ in range(100)]
print("List:", nums)

odds = [n for n in nums if n % 2 != 0]
print("Odd count:", len(odds))

evens = [n for n in nums if n % 2 == 0]
print("Even count:", len(evens))

def is_prime(x):
    if x < 2:
        return False
    for i in range(2, int(math.sqrt(x)) + 1):
        if x % i == 0:
            return False
    return True

primes = [n for n in nums if is_prime(n)]
print("Prime count:", len(primes))
print("Prime list:", primes)

freq = Counter(nums)
most_common = freq.most_common(1)[0]
print("Most frequent:", most_common[0], "occurs", most_common[1], "times")

#Q4
roll_number = 1024170348
digits = [int(x) for x in str(roll_number)[:8]]

A = {d*7 for d in digits}
B = {d*9 for d in digits}

print("Set A:", A)
print("Set B:", B)

print("Union:", A.union(B))
print("Intersection:", A.intersection(B))
print("A - B:", A.difference(B))
print("B - A:", B.difference(A))
# difference() shows one‑sided difference, symmetric_difference() shows both sides combined

print("Symmetric difference:", A.symmetric_difference(B))

print("A subset of B:", A.issubset(B))
print("B superset of A:", B.issuperset(A))

x = int(input("Enter a value to discard from A: "))
A.discard(x)
print("Updated A:", A)
# discard() is safer than remove() because it does not raise an error if the value is missing

#Q5
my_dict = {
    "name": "Akshat Prakash Singh",
    "roll_no": "1024170348",
    "branch": "CSE",
    "age": 20,
    "city": "Patiala"
}

my_dict["location"] = my_dict.pop("city")
my_dict["cgpa"] = 8.53
my_dict["age"] += 1
print("Updated dict:", my_dict)

dict_pop = my_dict.copy()
dict_del = my_dict.copy()

dict_pop.pop("branch")
print("After pop:", dict_pop)

del dict_del["branch"]
print("After del:", dict_del)

for k, v in my_dict.items():
    print(k, "→", v)

if "email" in my_dict:
    print("Email:", my_dict["email"])
else:
    print("Email key not found")

friend_dict = {
    "name": "Arjun",
    "roll_no": "1024170349",
    "branch": "ECE",
    "age": 21,
    "city": "Delhi"
}

merged = {**my_dict, **friend_dict}
print("Merged dict:", merged)

string_dict = {k: v for k, v in my_dict.items() if isinstance(v, str)}
print("Only string values:", string_dict)
